### ISSUE TITLE
about function-go

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/cloud-functions-go#12]
I have tried and it works very well and I love the idea of build my code using this architecture but I am concern about two stuff.
There will be a cloud-functions-go supported by google soon?
My environment is windows  OS . Exists a workaround to build on windows box.

Thanks

**Comment by iangudger** [comment]
I am working on a nicer development story related to #6.

**Comment by albertog** [comment]
will be release soon ?

**Comment by iangudger** [comment]
Sorry for the delay. I have an initial version almost ready.

**Comment by albertog** [comment]
Hi @iangudger some news about initial version?

**Comment by iangudger** [comment]
@albertog, do you want to review #14?

**Comment by albertog** [comment]
@iangudger I have tested and works very well.
