### ISSUE TITLE
currently only allow one main.go

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/cloud-functions-go#15]
I have tried to compile multiple .go files with make & make test and throw a error instead  if I use ``` go run main.go my_other_code.go ``` work ok, so I think is a matter of make stript. 
Thanks

**Comment by iangudger** [comment]
It might be worth creating a new package for your code. That was what I had in mind. Otherwise, you can modify the makefile to include your additional files.

**Comment by albertog** [comment]
thanks I have modified only was for alert for future release.

**Comment by iangudger** [comment]
I have no specific plans to address this.
