### ISSUE TITLE
there are any update?

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/cloud-functions-go#18]
We are using cloud-functions but lately it is apparently stopped someone can tell us some updated

thanks

**Comment by iangudger** [comment]
Could you try deploying a function with this [main.go](https://gist.github.com/iangudger/47abc9dba43f1a0bc4729edc981d60b5) and post here what it prints out?

**Comment by albertog** [comment]
May be I have not explain well. Cloud functions work very very well and I have no problement. I want to say there are several months without new commit and apparently the cloud-function-go project are stopped from glooglecloudplatform engineers.

**Comment by iangudger** [comment]
All of the core functionality works except logging. My solution to that problem is taking longer than expected, but there was a workaround posted on one of the issues. I am not aware of any other pressing issues. Is there anything in particular that you need?

**Comment by albertog** [comment]
we have to need.

1 logging (i know the workaround but is very complex)
2 will be available for windows
3 ensure if there a changed in google backend the api continue working
(google support)

Thanks
Albero


2017-11-14 19:02 GMT+01:00 Ian Gudger <notifications@github.com>:

**Comment by iangudger** [comment]
> 1 logging (i know the workaround but is very complex)

The simple to use solution is coming. Sorry for the delay.

> 2 will be available for windows

I don't think full native Windows support is worth the effort. Full support will probably always require a compatibility layer such as a VM or WSL. One area for improvement would be full Windows support for packaging.

> 3 ensure if there a changed in google backend the api continue working

I am here. I am continuing to provide best-effort support in this area. Please let me know if it breaks.

**Comment by albertog** [comment]
Ok Many thanks and congratulations for this powerful software.

Alberto

2017-11-14 19:27 GMT+01:00 Ian Gudger <notifications@github.com>:
