### ISSUE TITLE
Deployment failure: Operation interrupted.

### ISSUE THREAD

**Issue by pshevtsov** [GoogleCloudPlatform/cloud-functions-go#30]
When I tried to deploy `function.zip` I got the following error message on Google Cloud Functions:

> Deployment failure: Operation interrupted.

This is what I did:

At first, clone and build:
```console
$ git clone https://github.com/GoogleCloudPlatform/cloud-functions-go.git && cd cloud-functions-go
$ make
```
Then uploaded to Google Cloud Functions using the GCP web UI.

The following error entry is in the logs:

```javascript
{
 insertId:  "-uie6zkd1h36"  
 logName:  "projects/my-project-id/logs/cloudaudit.googleapis.com%2Factivity"  
 operation: {
  id:  "operations/aXBpbmZvLTE4MTYyMC91cy1jZW50cmFsMS9mdW5jdGlvbi0xL1YyWERCd1Z4ZGdr"   
  last:  true   
  producer:  "cloudfunctions.googleapis.com"   
 }
 protoPayload: {
  @type:  "type.googleapis.com/google.cloud.audit.AuditLog"   
  methodName:  "google.cloud.functions.v1.CloudFunctionsService.CreateFunction"   
  resourceName:  "projects/my-project-id/locations/us-central1/functions/function-1"   
  serviceName:  "cloudfunctions.googleapis.com"   
  status: {
   code:  10    
   message:  "Operation interrupted."    
  }
 }
 receiveTimestamp:  "2018-02-19T12:27:44.296923939Z"  
 resource: {
  labels: {
   function_name:  "function-1"    
   project_id:  "my-project-id"    
   region:  "us-central1"    
  }
  type:  "cloud_function"   
 }
 severity:  "ERROR"  
 timestamp:  "2018-02-19T12:27:43.703Z"  
}
```

**Comment by iangudger** [comment]
Maybe try again? I just tested the steps you listed and it worked for me.

**Comment by pshevtsov** [comment]
Yes, indeed, it worked. Probably it was some temporary GCP issue…

**Comment by otto-md** [comment]
I've run into the same problem. It spins for 5+minutes and then I get the same error. Ive tried three times, always the same problem.

I use `go1.10.1 darwin/amd64` and when I created the function in the console I picked `execute` as the function to execute. I guess that is the default from main.go in this repo?

**Comment by otto-md** [comment]
And now it worked. Fourth time...

**Comment by iangudger** [comment]
Do you have the most recent version? We did fix a flakiness issue. Post here if you experience it again.

**Comment by otto-md** [comment]
yes, i pulled the repo just minutes before i tried.

**Comment by iangudger** [comment]
I looked into it and I think that there is a reasonably high probability that it was a GCF issue. When the code in this project doesn't work correctly, typically deployment fails with an error about your function failing the heath check. I believe that the error described in this issue is a GCF internal error.

Next time this happens, try deploying a hello world JS function over the Go one and see if that works. If it works, try deploying the Go one again.

**Comment by otto-md** [comment]
For the last couple of days this is happening consistently again. Ive tried the following:

1. using gcloud command with gs:// source url. Didn't work.
2. web console with zip upload. Didn't work.
3. web console with inline js (always works), then replace with my function.zip. Didn't work.

Always with the `ERROR: (gcloud.beta.functions.deploy) OperationError: code=10, message=Operation interrupted.` error.

Any ideas?

**Comment by MrBhatt** [comment]
facing same error using node.js. Even with the sample google (default) functions, throwing same error since a few hours now.

**Comment by kz** [comment]
I'm currently facing the same issue with a slightly different environment.

I get this error after creating a _Firebase_ project, going to the _Google Cloud Platform_ console and uploading a function generated using `cloud-functions-go`. I also attempted to deploy a Firebase function via the GCP console by creating a _Firebase Cloud Function_ using `firebase init` and copying over files from `cloud-functions-go`. Attempts to (re-)deploy either functions fail.

@iangudger Given how @MrBhatt has coincidentally experienced this an hour ago, perhaps there may have been a backend configuration change leading to this?

**Comment by kz** [comment]
Perhaps there may have been an outage; I just reattempted a deploy and both functions worked!
It's good to see that Firebase functions also work.

**Comment by iangudger** [comment]
If it happens with pure JavaScript functions as well, it seems most likely that it is a problem with GCF.

**Comment by vcGF** [comment]
Today I am trying this and experiencing this issue as well.

I tried many times, over 10 times, and the link here [https://status.firebase.google.com/](https://status.firebase.google.com/) shows all services running properly

**Comment by vcGF** [comment]
Are you implying they made changes that are causing those endless "Operation interrupted" errors when trying to import a zip package ?

**Comment by vcGF** [comment]
I tried to give a look in the #go and the #functions channels there, didn't see anything exciting,  but I don't have access to the full history (yet).

@kz  Care to tell a bit more what you've read there ? :)

**Comment by GopikrishnanSasikumar** [comment]
Hey I am still having the problem. Any solution ?

**Comment by ptiger10** [comment]
Was experiencing this issue as well trying to deploy a Python 3.7 app. 

- First I made sure I had the most up-to-date SDK (`$ gcloud components update`). 

- Then I ran: `$ gcloud functions deploy FUNC_NAME --runtime python37 --trigger-http --entry-point handle`

- Spun for about 10 minutes, then returned `ERROR: (gcloud.functions.deploy) OperationError: code=10, message=Operation interrupted.` 

- Thought maybe it was a temporary bug last night, so re-ran this morning and still not working. 

I could see that it had tried to deploy by both (1) looking in the GCP console (the function was there but with an error notice) and (2) running:
`$ gcloud functions list`, which returned:
```
NAME       STATUS   TRIGGER       REGION
FUNC_NAME  UNKNOWN  HTTP Trigger  us-central1
```

I tried `$ gcloud functions deploy FUNC_NAME ... --region us-east1` and it worked immediately. 

Try changing the region?

**Comment by jonasdebeukelaer** [comment]
@GopikrishnanSasikumar looks like there the same issues have cropped up with GCF, as I've just started being unable to deploy some functions for the `operation interrupted` reason too

**Comment by fedosev** [comment]
Same problem

**Comment by iangudger** [comment]
Please try again now.

**Comment by jonasdebeukelaer** [comment]
yup better now, thanks 👍

**Comment by fedosev** [comment]
Works now, thanks

**Comment by waheedbrown** [comment]
FYI, you have to have a Google Cloud Storage (GCS) bucket created. Cloud Functions require a GCS bucket for staging. Without at least one available bucket, you will get that "unknown" error message

**Comment by SergeyRudakov** [comment]
Same Problem in one of the GCP projects (have 2 projects, deployment works on one proj and fails on any CF deployment on another):
Function's deployment in GCP console stops after 5 minutes with 
```
Deployment failure:
Operation interrupted.

```
error message. Stackdriver log says "ABORTED".
