### ISSUE TITLE
NodeJS, PassportJS or JWT in Google Cloud Functions

### ISSUE THREAD

**Issue by DerlysF** [GoogleCloudPlatform/cloud-functions-go#33]
Hello, I would like to know if it is possible to make an authentication system using nodejs with passportjs or JWT integrated with Google Cloud Functions, which I want to know exactly if doing the authentication in GCF I do not have to authenticate every time I do an action and yes only authenticate once

**Comment by iangudger** [comment]
Sorry, not sure.
