### ISSUE TITLE
Official Golang support plans?

### ISSUE THREAD

**Issue by Pushplaybang** [GoogleCloudPlatform/cloud-functions-go#36]
Not sure where to look for info on this, are there any plans for native support of Golang in google cloud functions?  Feels a bit silly that AWS Lambda beat them to this.

If this isn't the right place to ask, any ideas about where we should would be great.

**Comment by iangudger** [comment]
This is the place to ask:
https://issuetracker.google.com/issues/79362421

**Comment by Pushplaybang** [comment]
@iangudger  - thanks!  don't want to beat a dead horse though any intel on the current state of this?

**Comment by iangudger** [comment]
No, sorry.

**Comment by Pushplaybang** [comment]
bleak,  and it seem to be blocked by a non-public issue ://

**Comment by kz** [comment]
@Pushplaybang If you'd like information about any upcoming runtimes, it's worth joining the Google Cloud Platform Slack. I believe a product manager said (on one of the public channels) that Go runtime support is on the roadmap.

**Comment by iangudger** [comment]
https://cloud.google.com/blog/products/application-development/cloud-functions-go-1-11-is-now-a-supported-language
