### ISSUE TITLE
How to deploy function to local emulator?

### ISSUE THREAD

**Issue by Kane-Sendgrid** [GoogleCloudPlatform/cloud-functions-go#38]

**Comment by ssttevee** [comment]
If you mean using the `@google-cloud/functions-emulator`  npm package, you can't.

However, there is an alternative, which is described in the readme: https://github.com/GoogleCloudPlatform/cloud-functions-go#local-testing

TLDR: you'll probably want to run `make godev`

**Comment by Kane-Sendgrid** [comment]
Thanks, makes sense!
