### ISSUE TITLE
Can't get this package.

### ISSUE THREAD

**Issue by ando-masaki** [GoogleCloudPlatform/cloud-functions-go#41]
I can't get this package for following reason.

```
$ go get github.com/GoogleCloudPlatform/cloud-functions-go
../../../github.com/GoogleCloudPlatform/cloud-functions-go/main.go:22:2: local import "./nodego" in non-local package
```

How to use this package?

**Comment by ssttevee** [comment]
This package is meant to live outside of the `GOPATH`. So, you have to `git clone` this repo rather than `go get`ing it.

From there, your starting point is `main.go`. If you want to use the `events` sub-package, you must import `./events` which is a relative path.

**Comment by iangudger** [comment]
I just looked over the README, and while I think the information is there, I agree that it is more subtle than it should be. @ando-masaki, have you gotten it working? Do you want to try to clarify the instructions?
