### ISSUE TITLE
where put my code

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/cloud-functions-go#9]
I tested and work very nice but I have a doubt where should I place my code and how in other to be isolate of runtime code.

nodego.go ?
main.go ?
other

**Comment by salrashid123** [comment]
It should go into [main.go](
https://github.com/GoogleCloudPlatform/cloud-functions-go/blob/master/main.go#L27)

**Comment by albertog** [comment]
thanks for clarification
